candle_backend/users/views.py
from flask import Blueprint, redirect, request, url_for

from candle_backend.models import User
from flask_login import login_user, logout_user, current_user


users = Blueprint('users', __name__)  # Blueprint instancia



@users.route('/prihlasit', methods=['GET'])
def login():
    ais_login = 'grohol2'  # TODO treba implementovat CoSign prihlasenie cez AIS ('grohol2' je moj AIS login)
    user = User.query.filter_by(login=ais_login).first()
    if user:
        login_user(user, remember=True)  # defaultne si zapamatame usera, aby sa najblizsie nemusel zas prihlasovat
        #flash('Prihlasovanie prebehlo uspesne.')  # TODO (flash messages by boli krajsie ako nevypisat nic ...)

        #TODO mozno toto treba riesit cez "next" - co bude bezpecnejsie
        return redirect(request.referrer) if request.referrer else redirect(url_for("timetable.home"))

    else:
        ...
        #flash('Prihlasenie bolo neuspesne.')
        # TODO mozno lepsie je presmerovat / ukazat nejaku error page
    return redirect(request.referrer)   # vrati sa na stranku kde sme boli predtym


# TODO POUZIT POTOM TOTO ZNOVU!
# @users.route('/odhlasit', methods=['GET'])
# def logout():
#     logout_user()
#     return redirect(request.referrer)


# TODO zmazma!!!!
@users.route('/odhlasit', methods=['GET'])
def logout():
    logout_user()
    return redirect(url_for("timetable.home"))

candle_backend/templates/timetable/row_first.html
<div id="vrch_riadok1">
    <div id="vrch_riadok1_vpravo">
        <h2 class="pristupnost">Menu používateľa</h2>
        {% if current_user.is_authenticated %}
            <span class="username">{{ current_user.login }}</span>
        {% else %}
            <span class="username">anonymný návštevník</span>
        {% endif %}
    <ul>
     <li>
         {% if current_user.is_authenticated %}
             <a rel="nofollow" href="{{ url_for('users.logout') }}">Odhlásiť</a></li>
         {% else %}
             <a href="{{ url_for('users.login') }}">Prihlásiť</a></li>
         {% endif %}

        <li><a href="#">Zmeniť farby</a></li>
    </ul>
    </div>
    <div id="vrch_riadok1_vlavo">
        <h2 class="pristupnost">Linky</h2>
        <ul><!--
            --><li><a class="selected" href="/2016-2017-zima/">Rozvrh</a></li><!--
{#            --><li><a href="https://github.com/fmfi-svt/candle">Zoznam chýb</a></li><!--#}
{#            --><li><a href="https://github.com/fmfi-svt/candle/wiki">Dokumentácia</a></li><!--#}
{#            --><li><a href="https://github.com/fmfi-svt/candle/wiki/FAQ">FAQ</a></li><!--#}
            --><li><a href="http://groups.google.com/group/candle-users">Mailing list</a></li>
        </ul>
    </div>
</div>

candle_backend/templates/timetable/row_second.html
<div id="vrch2">
    <div id="vrch_riadok2">
        {% if current_user.is_authenticated %}
            <h2 class="pristupnost">Výber aktívneho rozvrhu</h2>
            <ul id="rozvrh_taby">
                {%- for ut in user_timetables -%}
                    <li><a rel="nofollow" href="{{ url_for('timetable.user_timetable', id_=ut.id_) }}"
                    {%- if selected_timetable_key == ut.id_ -%}
                       class="selected"
                    {%- endif -%}
                    >{{ ut.name }}</a></li>
                {%- endfor -%}
                <li><input type="button" id="novy_rozvrh" value="Nový rozvrh"></li>
            </ul>
            <h2 class="pristupnost">Akcie aktívneho rozvrhu</h2>
            <ul id="rozvrh_akcie">
{#                <li><a href="/rozvrh/453fyytyyyyyyyyyyyyyyttttttttt">453fyytyyyyyyyyyyyyyyttttttttt</a></li><li><a rel="nofollow" href="/moj/rozvrh/1/nezdielat">Nezdieľať</a></li><!--#}
{#                   <li id="menuSave"><a rel="nofollow" href="/moj/rozvrh/1/ulozit">Uložiť</a></li><!--#}      {# DG: Nepouzivame session, takze rozvrh sa uklada stale pri kazdej zmene automaticky. #}
                <li><a rel="nofollow" href="/moj/rozvrh/1/premenovat">Premenovať</a></li>
                <li><a href="javascript:window.print();" id="timetablePrintButton">Tlačiť</a></li><li id="menuPrintBefore"><a rel="nofollow" href="/moj/rozvrh/1/duplikovat">Duplikovať</a></li>
                <li><a rel="nofollow" href="/moj/rozvrh/1/importovat">Importovať</a></li>
                <li><a rel="nofollow" href="/moj/rozvrh/1/exportovat">Exportovať</a></li>
{#                <li><a id="delete" rel="nofollow" href="">Zmazať</a></li>#}
            <input type="button" id="zmazat_rozvrh" value="Zmazať">
            </ul>
        {% else %}
{#                ZATIAL NIC#}
        {% endif %}

    </div>
</div>

candle_backend/templates/timetable/timetable_list.html
{% block rozvrhList %}
    <table id="rozvrhList" class="vysledky_podrobneho_hladania">
    <tbody>
    <tr>
        <th>Deň</th>
        <th>Od</th>
        <th>Do</th>
        <th>Miestnosť</th>
        <th>Typ</th>
        <th>Kód</th>
        <th>Predmet</th>
        <th>Vyučujúci</th>
        <th>Poznámka</th>
    </tr>

    {% for lesson in timetable.get_lessons() %}
        <tr>
            <td>{{  lesson.get_day_abbr() }}</td>
            <td>{{  lesson.get_start() }}</td>
            <td>{{  lesson.get_end() }}</td>
            <td><a href="{{ url_for('rooms.timetable', room_name=lesson.room.name) }}">{{ lesson.room.name }}</a></td>
            <td>{{ lesson.type }} </td>
            <td>{{ lesson.subject.short_code }}</td>
            <td>
                {% if lesson.subject.short_code %}
                    <a href="{{ timetable.get_infolist_url(lesson.subject.short_code) }}.html">{{ lesson.subject.name }}</a>
                {% else %}
                       {{ lesson.subject.name }}
                {% endif %}
            </td>
            <td>
                {%  for teacher in lesson.teachers -%}
                    {% if teacher.slug %}
                        <a href="{{ url_for('teachers.timetable', teacher_slug=teacher.slug) }}">{{ teacher.short_name }}</a>
                        {%- if not loop.last -%}
                            {{ ', ' }}
                        {%- endif %}
                    {% endif %}
                {%- endfor %}
            </td>
            {% if lesson.note %}
                <td>{{ lesson.note }}</td>
            {% else %}
                <td></td>
            {% endif %}
        </tr>
    {% endfor %}
    </tbody>
    </table>
{% endblock %}

candle_backend/templates/timetable/top_row.html
<div id="vrch_riadok1">
    <div id="vrch_riadok1_vpravo">
        <h2 class="pristupnost">Menu používateľa</h2>
        {% if current_user.is_authenticated %}
            <span class="username">{{ current_user.login }}</span>
        {% else %}
            <span class="username">anonymný návštevník</span>
        {% endif %}
    <ul>
     <li>
         {% if current_user.is_authenticated %}
             <a rel="nofollow" href="{{ url_for('users.logout') }}">Odhlásiť</a></li>
         {% else %}
             <a href="{{ url_for('users.login') }}">Prihlásiť</a></li>
         {% endif %}

        <li><a href="#">Zmeniť farby</a></li>
    </ul>
    </div>
    <div id="vrch_riadok1_vlavo">
        <h2 class="pristupnost">Linky</h2>
        <ul><!--
            --><li><a class="selected" href="/2016-2017-zima/">Rozvrh</a></li><!--
{#            --><li><a href="https://github.com/fmfi-svt/candle">Zoznam chýb</a></li><!--#}
{#            --><li><a href="https://github.com/fmfi-svt/candle/wiki">Dokumentácia</a></li><!--#}
{#            --><li><a href="https://github.com/fmfi-svt/candle/wiki/FAQ">FAQ</a></li><!--#}
            --><li><a href="http://groups.google.com/group/candle-users">Mailing list</a></li>
        </ul>
    </div>
</div>