candle_backend/student_groups/routes.py
from flask import render_template, Blueprint

from ..helpers import get_student_groups_sorted_by_first_letter
from ..models import StudentGroup, Lesson

from .. import temporary_path, Timetable  # TODO presunut do config filu

student_groups = Blueprint('student_groups', __name__)



@student_groups.route(temporary_path + '/kruzky')
def list_student_groups():
    groups_list = StudentGroup.query.all()
    student_groups_dict = get_student_groups_sorted_by_first_letter(groups_list)

    return render_template('list_student_groups.html', student_groups_dict=student_groups_dict)


@student_groups.route(temporary_path + '/kruzky/<student_group_name>')
def timetable_student_group(student_group_name):
    """ Zobrazi rozvrh pre dany kruzok."""
    web_header = "Rozvrh krúžku " + student_group_name
    group = StudentGroup.query.filter_by(name=student_group_name).first()

    lessons = group.lessons.order_by(Lesson.day, Lesson.start).all()

    timetable = Timetable.Timetable(lessons)
    starting_times = timetable.get_starting_times()

    return render_template('timetable.html', student_group_name=student_group_name, lessons_list=lessons,
                           web_header=web_header, timetable=timetable, starting_times=starting_times)

candle_backend/teachers/routes.py
from flask import Blueprint, render_template

from ..helpers import get_teachers_sorted_by_family_name
from ..models import Lesson, Teacher
from .. import Timetable

from .. import temporary_path   # TODO presunut do config filu

teachers = Blueprint('teachers', __name__)

# Vypise vsetkych ucitelov (zoznam)
@teachers.route(temporary_path + '/ucitelia')
def list_teachers():
    """Vypise zoznam vsetkych ucitelov"""
    teachers_list = Teacher.query.order_by(Teacher.family_name).all()
    teachers_dict = get_teachers_sorted_by_family_name(teachers_list)

    return render_template('list_teachers.html', teachers_dict=teachers_dict)

@teachers.route(temporary_path + '/ucitelia/<teacher_slug>')
def timetable_teacher(teacher_slug):
    """ Zobrazi rozvrh daneho ucitela."""
    teacher = Teacher.query.filter_by(slug=teacher_slug).first()
    teacher_name = teacher.given_name + " " + teacher.family_name
    lessons = teacher.lessons.order_by(Lesson.day, Lesson.start).all()

    timetable = Timetable.Timetable(lessons)
    starting_times = timetable.get_starting_times()

    return render_template('timetable.html', teacher_name=teacher_name, lessons_list=lessons, title=teacher_name, web_header=teacher_name,
                           timetable=timetable, starting_times=starting_times)

candle_backend/templates/base_timetable.html
{# base_timetable.html #}
{# super-template pre vypisanie rozvrhu #}

{% extends "base.html" %}
    {% block rozvrhList %}
        <table id="rozvrhList" class="vysledky_podrobneho_hladania">
        <tbody>
        <tr>
            <th>Deň</th>
            <th>Od</th>
            <th>Do</th>
            <th>Miestnosť</th>
            <th>Typ</th>
            <th>Kód</th>
            <th>Predmet</th>
            <th>Vyučujúci</th>
            <th>Poznámka</th>
        </tr>

        {% for lesson in lessons %}
            <tr>
                <td>{{  lesson['day'] }}</td>
                <td>{{  lesson['start'] }}</td>
                <td>{{  lesson['end'] }}</td>
                <td><a href="{{ url_for('roomTimetable', room_name=lesson['room']) }}">{{ lesson['room'] }}</a></td>
                <td>{{ lesson['type'] }}</td>
                <td>{{ lesson['code'] }}</td>
                <td>
                    {% if lesson['type'] != 'Nezadaný typ' %}
                        <a href="https://sluzby.fmph.uniba.sk/infolist/SK/{{ lesson['code'] }}.html">{{ lesson['subject'] }}</a>
                    {% else %}
                        {{ lesson['subject'] }}
                    {% endif %}
                </td>
                <td>{{ lesson['note'] }}</td>
            <td>
                {% if lesson['teachers_dict'] %}
                    {%  for slug, short_name in lesson['teachers_dict'].items() -%}
                        <a href="{{ url_for('teacherTimetable', teacher_slug=slug) }}">{{ short_name }}</a>
                        {%- if not loop.last -%}
                            {{ ', ' }}
                        {%- endif %}
                    {%- endfor %}
                {% endif %}
            </td>
            </tr>
        {% endfor %}
        </tbody>
        </table>
    {% endblock %}

candle_backend/templates/list_student_groups.html
{# Vypise vsetky kruzky #}

{% extends "base.html"%}

{% block title %}Rozvrhy krúžkov{% endblock %}

{% block web_header %}Rozvrhy krúžkov{% endblock %}
{% block obsah_in %}
    {{ super() }}
        <p>
            {% for category in student_groups_dict %}
            <a href="#{{ category }}">{{ category }}</a>
            {% endfor %}
        </p>

    {# Kategorie miestnosti: #}
        {% for category in student_groups_dict %}
        <h2 id="{{ category }}">{{ category }}</h2>
            <ul>
                {% for group in student_groups_dict[category] -%}
                    <li><a href="{{ url_for('student_groups.timetable_student_group', student_group_name=group.name) }}">{{ group.name }}</a></li>
                {%-  endfor %}
            </ul>
        {% endfor %}
{% endblock %}

candle_backend/templates/show_all_rooms.html
{# Vypise vsetky miestnosti #}

{% extends "base.html" %}
{% block title %}Rozvrhy miestností{% endblock %}

{% block web_header %}Rozvrhy miestností{% endblock %}
{% block obsah_in %}
    {{ super() }}

        <p>
            {% for room_prefix in rooms_dict %}
            <a href="#{{ room_prefix }}">{{ room_prefix }}</a>
            {% endfor %}
        </p>

    {# Kategorie miestnosti: #}
        {% for room_prefix in rooms_dict %}
        <h2 id="{{ room_prefix }}">{{ room_prefix }}</h2>

            <ul>
                {% for room in rooms_dict[room_prefix] %}
                <li><a href="{{ url_for('roomTimetable', room_name = room) }}">{{ room }}</a></li>
                {%  endfor %}
            </ul>

        {% endfor %}

{% endblock %}

candle_backend/templates/show_all_teachers.html
{# Vypise vsetkych ucitelov #}

{% extends "base.html" %}
{% block title %}Rozvrhy učiteľov{% endblock %}

{% block web_header %}Rozvrhy učiteľov{% endblock %}
{% block obsah_in %}
    {{ super() }}
        <p>
            {% for first_letter in teachers_dict %}
            <a href="#{{ first_letter }}">{{ first_letter }}</a>
            {% endfor %}
        </p>

    {# Kategorie miestnosti: #}
        {% for category_key in teachers_dict %}
        <h2 id="{{ category_key }}">{{ category_key }}</h2>

            <ul>
                {% for teacher in teachers_dict[category_key] -%}
                    <li><a href="{{ url_for('teacherTimetable', teacher_slug=teacher.slug) }}">{{ teacher.family_name }}
                    {%- if teacher.given_name -%}
                        {{ ', ' }}{{ teacher.given_name }}
                    {%- endif -%}
                    </a></li>
                {%-  endfor %}
            </ul>
        {% endfor %}


{% endblock %}

candle_backend/templates/timetable.html
{# base_timetable.html #}
{# parent-template pre vypisanie rozvrhu #}
{% extends "base.html" %}


{% macro print_empty_cell(list) -%}
    <td class="{{ list| join(' ') }}"></td>
{%- endmacro %}


{% macro print_lesson(list, rowspan, title) -%}
    <td class="{{ list| join(' ') }}" rowspan="{{ rowspan }}"
{%- endmacro %}


{% macro print_day_headers() -%}
    {# Vypise hlavicku tabulky - dni v tyzdni - s pozadovanymi sirkami stlpcov. #}
    {% for day, columns_count in timetable.get_columns_count().items() %}
        {% if columns_count == 1 %}
            <th>{{ day }}</th>
        {% else %}
            <th colspan="{{ columns_count }}">{{ day }}</th>
        {% endif %}
    {% endfor %}
{%- endmacro %}

{% macro print_lesson_title(lesson) -%}
    title="
    {{ lesson.room.name }}, {{ lesson.get_day_abbr() }} {{ lesson.get_start() }}-{{ lesson.get_end() }}, {{ lesson.subject.short_code }}:
    {% for teacher in lesson.teachers -%}
        {{ teacher.get_short_name() }}
        {%- if not loop.last -%}
            {{ ', ' }}
        {%- endif %}
    {%- endfor %}
    ">
{%- endmacro %}


{#{% macro test_variable(variable) -%}#}
{#    {% if variable is none %}#}
{#    --- VARIABLE {{ variable }} IS NONE!!! ---#}
{#    {% endif %}#}
{#{%- endmacro %}#}


{% block title %}{{ title }}{% endblock %}
{% block web_header %}{{ web_header }}{% endblock %}

    {% block rozvrh %}

        {% set ns = namespace() %}
        {% set ns.layout = timetable.get_layout() %}

        <table id="rozvrh">
                <tr>
                    <th class="zaciatok"><span class="pristupnost">Začiatok</span></th>
                    {{ print_day_headers() }}
                </tr>

                {# Pre kazdy cas z pola starting_times: #}
                {% for  time_in_minutes, time in starting_times.items() %}
                    {# vypis cas #}
                    <tr class="startTimeHeader">
                        <td class="cas">{{ time }}</td>

                    {# pre kazdy den: #}
                    {%- for day in ns.layout -%}
                        {% set day_loop = loop %}
                        {# pre kazdy stlpec: #}
                        {%- for column in day -%}
                            {% set column_loop = loop %}

                            {% set ns.classes = [] %}
                            {# ak je to prvy stlpec #}
                            {% if loop.index0 == 0 %}
                                {% do ns.classes.append('startOfDayColumn') %}
                            {% endif %}

                            {# ak je to posledny stlpec#}
                            {% if loop.last %}
                                {% do ns.classes.append('endOfDayColumn') %}
                            {% endif %}

                            {# ak je stlpec prazdny alebo sme v nom presli uz vsetky hodiny#}
                            {% if column| length == 0 %}
                                {% do ns.classes.append('emptyCell') %}

                                {{ print_empty_cell(ns.classes) }}
                                {% continue %}
                            {% endif %}

                            {# Ak mame nejaku hodinu co prave zacina: #}
                            {% if time_in_minutes in column %}

                                {# ziskame hodinu: #}
                                {% set ns.lesson = timetable.get_lesson(day_loop.index0, column_loop.index0, time_in_minutes) %}

                                {# poznacime, ze hodina zacala: #}
                                {% do timetable.start_lesson(day_loop.index0, column_loop.index0, time_in_minutes) %}
                                {# TODO over ci je highlighted #}

                                {% do ns.classes.append('hodina') %}


                                {% set type_str = 'lesson-type-' ~  ns.lesson.type.code| upper() %}
                                {% do ns.classes.append(type_str) %}

                                {#  TODO nastavit TimeInfo, lessonTitle #}

                                {{ print_lesson(ns.classes, ns.lesson.get_rowspan()) }}
                                {{ print_lesson_title(ns.lesson) }}

                                {#  Vnutro bunky: #}
                                {% include "timetable_cell.html" %}

                                </td>
                            {% elif timetable.lesson_in_progress(time_in_minutes, day_loop.index0, column_loop.index0)%}   {#  AK PRECHADZAME CEZ HODINU:
                                {# TODO zmazat; Zrejme nebudeme potrebovat (mazanie uz prejdenych hodin z __layout): #}
                                {# Skontrolujeme, ci v danom stlpci ma este bezat hodina: #}
{#                                {% do timetable.check_lesson_progress(time_in_minutes, day_loop.index0, column_loop.index0) %}#}

                            {% else %}  {# Inak vypiseme prazdnu bunku #}
                                {%  do ns.classes.append('emptyCell') %}
                                {{ print_empty_cell(ns.classes) }}
                            {% endif %}

                        {%- endfor -%}
                    {%- endfor -%}

                    </tr>
                {% endfor %}



            </tbody>
        </table>

    {% endblock %}


    {% block rozvrhList %}
        <table id="rozvrhList" class="vysledky_podrobneho_hladania">
        <tbody>
        <tr>
            <th>Deň</th>
            <th>Od</th>
            <th>Do</th>
            <th>Miestnosť</th>
            <th>Typ</th>
            <th>Kód</th>
            <th>Predmet</th>
            <th>Vyučujúci</th>
            <th>Poznámka</th>
        </tr>

        {% for lesson in lessons_list %}
            <tr>
                <td>{{  lesson.get_day_abbr() }}</td>
                <td>{{  lesson.get_start() }}</td>
                <td>{{  lesson.get_end() }}</td>
                <td><a href="{{ url_for('rooms.timetable_room', room_name=lesson.room.name) }}">{{ lesson.room.name }}</a></td>
                <td>{{ lesson.type }} </td>
                <td>{{ lesson.subject.short_code }}</td>
                <td>
                    {% if lesson.subject.short_code %}
                        <a href="{{ timetable.get_infolist_url(lesson.subject.short_code) }}.html">{{ lesson.subject.name }}</a>
                    {% else %}
                           {{ lesson.subject.name }}
                    {% endif %}
                </td>
                <td>
                    {%  for teacher in lesson.teachers.all() -%}
                        {% if teacher.slug %}
                            <a href="{{ url_for('teachers.timetable_teacher', teacher_slug=teacher.slug) }}">{{ teacher.get_short_name() }}</a>
                            {%- if not loop.last -%}
                                {{ ', ' }}
                            {%- endif %}
                        {% endif %}
                    {%- endfor %}
                </td>
                {% if lesson.note %}
                    <td>{{ lesson.note }}</td>
                {% else %}
                    <td></td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
        </table>
    {% endblock %}