candle/entities/room/views.py
from flask import render_template, Blueprint
from flask_login import current_user

from candle.models import Room, Lesson, Subject
from candle.timetable import timetable
from typing import Dict


room = Blueprint('room',
                 __name__,
                 template_folder='templates')


@room.route('/miestnosti')
def list_rooms():
    """Show all rooms."""
    rooms_list = Room.query.order_by(Room.name).all()
    rooms_dict = get_rooms_sorted_by_dashes(rooms_list)  # rooms are in the dictionary sorted by prefix
    title = "Rozvrhy miestností"
    return render_template('room/list_rooms.html', rooms_dict=rooms_dict, title=title,
                           web_header=title)


@room.route('/miestnosti/<room_url_id>')
def show_timetable(room_url_id):
    """Show a timetable for a room."""
    if room_url_id.isnumeric():
        room = Room.query.filter_by(id_=room_url_id).first_or_404()
    else:
        room = Room.query.filter_by(name=room_url_id).first_or_404()
    web_header = "Rozvrh miestnosti " + room.name

    lessons = room.lessons.join(Subject).order_by(Lesson.day, Lesson.start, Subject.name).all()
    t = timetable.Timetable(lessons)
    if current_user.is_authenticated:
        user_timetables = current_user.timetables
    else:
        user_timetables = None
    return render_template('timetable/timetable.html', room_name=room.name, title=room.name,
                           timetable=t, user_timetables=user_timetables, show_welcome=False,
                           web_header=web_header)


def get_rooms_sorted_by_dashes(rooms_lst) -> Dict:
    """
    Return OrderedDict that contains rooms sorted by categories.

    The key in the OrderedDict is always the room prefix and the values are rooms (objects of model Room)
     (For example'F1-108' has prefix 'F1').

    :parameter rooms_lst: The list of the Room model objects.
    :return OrderedDict (dict of str: list), where key is the prefix and the value is a list of Rooms.
    """
    d = {}
    for room in rooms_lst:
        url_id = room.url_id
        if url_id == " ":   # we have one room with empty name (" ")
            continue
        prefix = room.prefix

        # insert data into dictionary:
        if prefix not in d:
            d[prefix] = []
        d[prefix].append(room)

    return d

candle/templates/timetable/timetable.html
{% extends "base.html" %}

{% block timetable_menu %}
    {% if current_user.is_authenticated %}
        {% include('timetable/tabs_and_actions.html') %}
    {% endif %}
{% endblock %}

{% block obsah %}
    {% if show_welcome %}
        <div id="welcome">
            <h2>Vitajte v systéme Candle!</h2>
            <p>Vyhľadajte rozvrh v ľavom paneli,</p>
            <p> alebo sa <a href="{{ url_for('auth.login') }}">prihláste</a> a budete si môct vytvárať vlastné rozvrhy.</p>
        </div>
    {% else %}
        <div id="rozvrh">
            {% include('timetable/timetable_content.html') %}
        </div>
        <table id="rozvrhList" class="vysledky_podrobneho_hladania">
            {% include('timetable/list.html') %}
        </table>
    {% endif %}
{% endblock %}


{% block panel %}
    {% include 'panel/panel.html' %}
{% endblock %}

{% block script %}
    {{ super() }}
    <script src={{ url_for('static', filename='js/timetable_manager.js') }}></script>
    <script src={{ url_for('static', filename='js/panel.js') }}></script>
    <script src={{ url_for('static', filename='js/search.js') }}></script>
{% endblock %}

candle/templates/timetable/timetable_cell.html
{######################  MACROs #####################}
{% macro print_lesson_type(lesson) -%}
    {{ "lesson-type-" + lesson.type.code| upper()}}
{%- endmacro %}

{#TODO We will use this macro later, when we will no more use 1:1 testing with old Candle.#}
{#{% macro print_lesson_title(lesson) -%}#}
{#    {{ lesson.room.name }}, {{ lesson.get_day_abbr() }} {{ lesson.get_start() }}-{{ lesson.get_end() }}#}
{#    {%- if lesson.subject.short_code -%}#}
{#    {{", " + lesson.subject.short_code }}#}
{#    {%- endif -%}#}
{#    {%- if lesson.teachers -%}#}
{#        {{ ":" }}#}
{#        {% for teacher in lesson.teachers -%}#}
{#            {{ teacher.short_name }}#}
{#            {%- if not loop.last -%}#}
{#                {{ ', ' }}#}
{#            {%- endif %}#}
{#        {%- endfor %}#}
{#    {%- endif -%}#}
{#{%- endmacro %}#}

{% macro print_lesson_title(lesson) -%}
    {{ lesson.room.name }}, {{ lesson.day_abbreviated }} {{ lesson.start_formatted }}-{{ lesson.end_formatted }}, {{ lesson.subject.short_code }}:
    {% for teacher in lesson.teachers -%}
        {{ teacher.short_name }}
        {%- if not loop.last -%}
            {{ ', ' }}
        {%- endif %}
    {%- endfor %}
{%- endmacro %}
{##################### (end of) MACROs #####################}


<div class="hodina {{ print_lesson_type(placed_lesson.lesson) }}" style="{{ placed_lesson.get_css_style }}" title="{{ print_lesson_title(placed_lesson.lesson) }}">
    <div class="wrap">
        <div class="predmet_wrap">
            <div class="predmet">{{ placed_lesson.lesson.subject.name }}</div>
        </div>
        <div class="hodina_info">
            <div class="miestnost">
                <a href="{{ url_for('room.show_timetable', room_url_id=placed_lesson.lesson.room.name) }}">{{ placed_lesson.lesson.room.name }}</a>
            </div>
            <div class="typ">
                <abbr title="{{ placed_lesson.lesson.type.name }}">{{ placed_lesson.lesson.type.code| upper()}}</abbr>
            </div>
            <div class="infolist">
                <a href="{{ timetable.get_infolist_url(placed_lesson.lesson.subject.short_code) }}" title="Prejsť na informačný list."><i class="fa fa-info-circle" aria-hidden="true"></i></a>
            </div>
        </div>

    </div>
</div>

candle/templates/timetable/timetable_content.html
{######################  MACROs #####################}
{% macro print_empty_cell(list) -%}
    <td class="{{ list| join(' ') }}"></td>
{%- endmacro %}

{% macro print_lesson(list, rowspan, title) -%}
    <td class="{{ list| join(' ') }}" rowspan="{{ rowspan }}"
{%- endmacro %}

{% macro print_day_headers() -%}
    {% for day in timetable.get_days() -%}
        <div class="row1 day-header">{{ day }}</div>
    {%- endfor %}
{%- endmacro %}
{##################### (end of) MACROs #####################}


{% set ns = namespace() %}
{% set ns.layout = timetable.get_layout() %}

{# ##################### TODO nazov row1 by som zmenil na 'HEADERS'#}
<div class="row1" id="timetable-corner"></div>
{{ print_day_headers() }}
{# ##################### TODO nazov row2 by som zmenil na 'COLUMNS'#}
<div class="row2 times-column">
    {# Pre kazdy cas z pola starting_times: #}
    {% for time in timetable.get_starting_times() -%}
        <div class="start-time">{{ time }}</div>
    {%- endfor %}
</div>
{#Pre kazdy den:#}
{% for day in timetable.get_layout() -%}
    <div class="row2 day-column" style="background-image:
        repeating-linear-gradient(
                to bottom,
                transparent 1px,
                transparent  calc( {{ 100 / timetable.get_starting_times()| length }}% - 1px ),
                silver       calc( {{100 / timetable.get_starting_times()|length }}% + 1px )
            );
    background-size: 100% 100%;">
        {% for column in day -%}
            {% for placed_lesson in column -%}
                {% include "timetable/timetable_cell.html" %}
            {%- endfor %}
        {%- endfor %}
    </div>
{%- endfor %}